-- Insert all pages for Wiki.js knowledge base structure
-- Run: docker exec -i your-postgres-container psql -U wikijs -d wikijs < this_file.sql

INSERT INTO pages (path, hash, title, description, "isPrivate", "isPublished", content, render, "contentType", "createdAt", "updatedAt", "editorKey", "localeCode", "authorId", "creatorId", "publishStartDate", "publishEndDate")
VALUES
('home',                        'h0',  '首页',             '跨境电商技术运维知识库',                 false, true, '# 首页\n\n跨境电商技术运维知识库',                        '# 首页\n\n跨境电商技术运维知识库',                        'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/inbox',                  'h1',  '收件箱',           '文档暂存区，上传后自动分析归类到对应目录', false, true, '# 收件箱\n\n文档暂存区',                                '# 收件箱\n\n文档暂存区',                                'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ops',                    'h2',  '服务器运维',       '服务器、容器、网络、数据库运维文档',       false, true, '# 服务器运维\n\n运维文档',                              '# 服务器运维\n\n运维文档',                              'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ops/servers',            'h3',  '服务器清单与架构', 'VPS配置、网络拓扑、服务架构',               false, true, '# 服务器清单与架构\n\nVPS配置',                        '# 服务器清单与架构\n\nVPS配置',                        'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ops/docker',             'h4',  'Docker容器管理',   '容器部署、compose、镜像管理',               false, true, '# Docker容器管理\n\n容器部署',                         '# Docker容器管理\n\n容器部署',                         'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ops/nginx',              'h5',  'Nginx反代与域名',  '站点配置、SSL证书、反代规则',               false, true, '# Nginx反代与域名\n\n站点配置',                       '# Nginx反代与域名\n\n站点配置',                       'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ops/database',           'h6',  '数据库PostgreSQL', '数据库维护、备份、查询',                     false, true, '# 数据库PostgreSQL\n\n数据库维护',                    '# 数据库PostgreSQL\n\n数据库维护',                    'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ops/backup',             'h7',  '备份与恢复',       '数据备份策略与恢复流程',                     false, true, '# 备份与恢复\n\n备份策略',                              '# 备份与恢复\n\n备份策略',                              'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ops/monitor',            'h8',  '监控与告警',       '服务监控、告警配置、日常检查',               false, true, '# 监控与告警\n\n服务监控',                              '# 监控与告警\n\n服务监控',                              'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ops/incidents',          'h9',  '故障处理记录',     '历史故障与解决方案',                         false, true, '# 故障处理记录\n\n历史故障',                            '# 故障处理记录\n\n历史故障',                            'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ecommerce',              'h10', '跨境电商',         'Amazon运营与数据分析',                       false, true, '# 跨境电商\n\nAmazon运营',                              '# 跨境电商\n\nAmazon运营',                              'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ecommerce/amazon',       'h11', 'Amazon运营',       'Listing优化、广告、竞品分析',                false, true, '# Amazon运营\n\nListing广告竞品',                     '# Amazon运营\n\nListing广告竞品',                     'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ecommerce/amazon/listing','h12','Listing优化SOP',    '标题、五点、描述、A+内容优化标准',           false, true, '# Listing优化SOP\n\n优化标准',                         '# Listing优化SOP\n\n优化标准',                         'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ecommerce/amazon/competitor','h13','竞品分析框架',  '竞品监控方法与分析工具',                     false, true, '# 竞品分析框架\n\n竞品监控',                            '# 竞品分析框架\n\n竞品监控',                            'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ecommerce/amazon/keywords','h14','关键词研究',      '关键词挖掘与排名跟踪',                       false, true, '# 关键词研究\n\n关键词排名',                            '# 关键词研究\n\n关键词排名',                            'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ecommerce/amazon/ads',    'h15','广告投放策略',      'SP、SB、SD广告优化方法',                     false, true, '# 广告投放策略\n\nSP SB SD',                           '# 广告投放策略\n\nSP SB SD',                           'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ecommerce/data',          'h16','数据分析',          '销售数据、流量数据、库存分析',               false, true, '# 数据分析\n\n销售流量库存',                            '# 数据分析\n\n销售流量库存',                            'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ecommerce/supplychain',   'h17','供应链与物流',      'FBA库存管理、供应商管理',                     false, true, '# 供应链与物流\n\nFBA供应商',                           '# 供应链与物流\n\nFBA供应商',                           'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ai',                      'h18','AI与自动化',        'n8n工作流、AI应用、Prompt工程',              false, true, '# AI与自动化\n\nn8n Prompt Dify',                      '# AI与自动化\n\nn8n Prompt Dify',                      'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ai/n8n',                  'h19','n8n工作流清单',     '所有自动化工作流记录与说明',                 false, true, '# n8n工作流清单\n\n所有工作流',                        '# n8n工作流清单\n\n所有工作流',                        'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ai/prompts',              'h20','AI Prompt库',       '各场景Prompt模板与优化记录',                 false, true, '# AI Prompt库\n\nPrompt模板',                          '# AI Prompt库\n\nPrompt模板',                          'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ai/dify',                 'h21','Dify应用',          'Dify上部署的AI应用',                         false, true, '# Dify应用\n\nAI应用',                                  '# Dify应用\n\nAI应用',                                  'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ai/models',               'h22','模型评测与对比',    '各AI模型能力对比与选型',                     false, true, '# 模型评测与对比\n\nAI模型选型',                       '# 模型评测与对比\n\nAI模型选型',                       'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/ai/external',             'h23','外部AI服务',        '第三方AI API与工具',                          false, true, '# 外部AI服务\n\n第三方API',                              '# 外部AI服务\n\n第三方API',                              'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/dev',                     'h24','开发笔记',          'API文档、脚本工具、开发记录',                false, true, '# 开发笔记\n\nAPI脚本',                                 '# 开发笔记\n\nAPI脚本',                                 'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/dev/api',                 'h25','API接口文档',       '各服务API接口说明',                           false, true, '# API接口文档\n\n接口说明',                             '# API接口文档\n\n接口说明',                             'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/dev/scripts',             'h26','脚本与工具',        '自动化脚本、辅助工具',                       false, true, '# 脚本与工具\n\n自动化脚本',                            '# 脚本与工具\n\n自动化脚本',                            'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', ''),
('home/dev/pitfalls',            'h27','踩坑记录',          '开发过程中遇到的问题与解决方案',             false, true, '# 踩坑记录\n\n问题解决',                                '# 踩坑记录\n\n问题解决',                                'markdown', NOW()::text, NOW()::text, 'markdown', 'zh', 1, 1, '', '');
